name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/vatcalc
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Debug directory contents
        run: |
          pwd
          ls -la
          cat pyproject.toml
        
      - name: Install build package
        run: |
          uv pip install --system build
          python -m pip list
        
      - name: Build package
        run: |
          which python
          python -m build --sdist --wheel .
        
      - name: List dist contents
        run: ls -la dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
